vim.cmd("set expandtab")
vim.cmd("set nu")
vim.cmd("set rnu")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set breakindent")
vim.cmd("set linebreak")
vim.cmd("set hlsearch")
vim.cmd("set clipboard+=unnamedplus")
--vim.cmd("set spell")
--vim.cmd("setlocal spell spelllang=en_us")
--vim.g.mapleader =  
vim.keymap.set("n", "<C-b>", "<cmd>wall<cr><esc> <bar> :below split term:// g++ % -o out && ./out < in.txt <Return> <bar> :wincmd 4- <Return> :1 <Return>")
--vim.keymap.set("n", "<Esc>", ":close")
vim.api.nvim_create_user_command("CP", "cd /home/meowx2/cp/ <bar> edit main.cpp <bar> :vsplit in.txt <bar> :wincmd L <bar> :wincmd 40< <bar> :wincmd h", {})

